
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: AromaLife_Container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: AromaLife_Container_docker
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1125288150@u.icesi.edu.co
      PGADMIN_DEFAULT_PASSWORD: hola1234
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin