#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose-plugin
runcmd:
  - [ bash, -lc, "usermod -aG docker ${admin_username} || true" ]
  - [ bash, -lc, "systemctl enable docker && systemctl start docker" ]
  - [ bash, -lc, "mkdir -p /opt/sonarqube && cd /opt/sonarqube" ]
  - [ bash, -lc, "cat > /opt/sonarqube/docker-compose.yml << 'EOF'\nversion: '3.8'\nservices:\n  db:\n    image: postgres:14\n    container_name: sonarqube-postgres\n    environment:\n      POSTGRES_USER: sonarqube\n      POSTGRES_PASSWORD: ${pg_password}\n      POSTGRES_DB: sonarqube\n    volumes:\n      - pg_data:/var/lib/postgresql/data\n    restart: unless-stopped\n  sonarqube:\n    image: sonarqube:community\n    container_name: sonarqube\n    depends_on:\n      - db\n    ports:\n      - '9000:9000'\n    environment:\n      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube\n      SONAR_JDBC_USERNAME: sonarqube\n      SONAR_JDBC_PASSWORD: ${pg_password}\n      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'\n    volumes:\n      - sonarqube_data:/opt/sonarqube/data\n      - sonarqube_extensions:/opt/sonarqube/extensions\n      - sonarqube_logs:/opt/sonarqube/logs\n    restart: unless-stopped\nvolumes:\n  pg_data: {}\n  sonarqube_data: {}\n  sonarqube_extensions: {}\n  sonarqube_logs: {}\nEOF" ]
  - [ bash, -lc, "docker compose -f /opt/sonarqube/docker-compose.yml up -d" ]
