#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose-plugin
write_files:
  - path: /opt/sonarqube/docker-compose.yml
    permissions: '0644'
    owner: root:root
    content: |
      version: '3.8'
      services:
        db:
          image: postgres:14
          container_name: sonarqube-postgres
          environment:
            POSTGRES_USER: sonarqube
            POSTGRES_PASSWORD: "${pg_password}"
            POSTGRES_DB: sonarqube
          volumes:
            - pg_data:/var/lib/postgresql/data
          restart: unless-stopped
        sonarqube:
          image: sonarqube:community
          container_name: sonarqube
          depends_on:
            - db
          ports:
            - '9000:9000'
          environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
            SONAR_JDBC_USERNAME: sonarqube
            SONAR_JDBC_PASSWORD: "${pg_password}"
            SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
          volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
          restart: unless-stopped
      volumes:
        pg_data: {}
        sonarqube_data: {}
        sonarqube_extensions: {}
        sonarqube_logs: {}
runcmd:
  - [ bash, -lc, "usermod -aG docker ${admin_username} || true" ]
  - [ bash, -lc, "systemctl enable docker && systemctl start docker" ]
  - [ bash, -lc, "mkdir -p /opt/sonarqube" ]
  - [ bash, -lc, "for i in {1..30}; do docker info && break || (echo 'Docker not ready yet'; sleep 2); done" ]
  - [ bash, -lc, "docker compose -f /opt/sonarqube/docker-compose.yml up -d || (echo 'Compose up failed' && docker logs $(docker ps -aq) || true)" ]
