name: infra-sonarqube

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_USE_OIDC: true
      ARM_SKIP_PROVIDER_REGISTRATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/terraform
        env:
          TF_VAR_enable_password_auth: 'true'
          TF_VAR_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/terraform
        env:
          TF_VAR_enable_password_auth: 'true'
          TF_VAR_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}
        run: terraform apply -input=false -auto-approve tfplan

      - name: Output Sonar URL
        id: tf_output
        working-directory: infra/terraform
        run: |
          echo "sonar_url=$(terraform output -raw sonarqube_url)" >> $GITHUB_OUTPUT

      - name: Expose Sonar URL
        run: echo "SonarQube URL is ${{ steps.tf_output.outputs.sonar_url }}"
